version: '3.1'

services:
  mongo:
    container_name: mongodb
    image: mongo:6.0.12-rc1
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: <login>
      MONGO_INITDB_ROOT_PASSWORD: <passw>
    volumes:
      - ./data_db:/data/db
    ports:
      - 27000:27017
